version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2404:current
      docker_layer_caching: true
    steps:
      - checkout
      - run: 
          name: Instalacja zaleznosci
          command: make deps
      - run: 
          name: Sprawdzanie czystosci kodu (Lint)
          command: make lint
      - run: 
          name: Uruchamianie testow
          command: make test
      - run:
          name: Budowanie obrazu Docker
          command: make docker_build
      - run:
          name: Wysylanie obrazu na Docker Hub
          command: make docker_push

workflows:
  basic:
    jobs:
      - build-and-test